#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -euo pipefail

if [[ -z ${LSIO_NON_ROOT_USER:-} ]]; then
  exec s6-setuidgid abc /usr/local/bin/abs-tracked-sync
fi

exec /usr/local/bin/abs-tracked-sync
