#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -euo pipefail

mkdir -p \
  "${DATADIR}" \
  /config/log/mysql \
  /config/backups \
  "${ABS_CONFIG_DIR}" \
  /run/mysqld

if [[ ! -f /config/custom.cnf ]]; then
  cp /defaults/custom.cnf /config/custom.cnf
fi

if [[ ! -f "${ABS_CONFIG_DIR}/targets.json.example" ]]; then
  cp /defaults/targets.json.example "${ABS_CONFIG_DIR}/targets.json.example"
fi

if [[ -f /run/mysqld/mysqld.pid ]]; then
  rm -f /run/mysqld/mysqld.pid
fi
